NEUTRAL:
    v: 0
    ideology: neutral
HIGHMEN:
    v: 1
    mask: 1
    ideology: good
BARBARIANS:
    v: 2
    mask: 2
    ideology: evil
WIZARDS:
    v: 3
    mask: 4
    ideology: good
BEASTMEN:
    v: 4
    mask: 8
    ideology: evil
ELVES:
    v: 5
    mask: 16
    ideology: good
UNDEADS:
    v: 6
    mask: 32
    ideology: evil