water:
    v: 0
    mask: 1
    moveCost: 255
    color:
        r: 8
        g: 28
        b: 128
sand:
    v: 1
    mask: 2
    moveCost: 12
    color:
        r: 214
        g: 182
        b: 148
dirt:
    v: 2
    mask: 4
    moveCost: 6
    color:
        r: 99
        g: 48
        b: 8
grass:
    v: 3
    mask: 8
    moveCost: 6
    color:
        r: 24
        g: 97
        b: 16
swamp:
    v: 4
    mask: 16
    moveCost: 14
    color:
        r: 0
        g: 44
        b: 0
lava:
    v: 5
    mask: 32
    moveCost: 10
    color:
        r: 48
        b: 48
        g: 48
wasteland:
    v: 6
    mask: 64
    moveCost: 8
    color:
        r: 165
        b: 85
        g: 16
desert:
    v: 7
    mask: 128
    moveCost: 12
    color:
        r: 181
        b: 138
        g: 24
snow:
    v: 8
    mask: 256
    moveCost: 10
    color:
        r: 220
        b: 220
        g: 220
new_desert:
    v: 9
    mask: 512
    moveCost: 12
    color:
        r: 192
        b: 160
        g: 0
pavement:
    v: 10
    mask: 1024
    moveCost: 4
    color:
        r: 160
        b: 160
        g: 160
new_wasteland:
    v: 11
    mask: 2048
    moveCost: 9
    color:
        r: 192
        b: 192
        g: 160