name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  main:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master code
        uses: actions/checkout@v2
        with:
          path: master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build project
        run: |
          cd master
          ./gradlew :jsBrowserProductionWebpack
          rm build/distributions/*.map
      - name: Checkout gh-pages code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy distribution to gh-pages
        run: |
          cp -r master/build/distributions/* gh-pages  # todo: remove old content: omit merging and perform replacing
      - name: Commit and push
        run: |
          cd gh-pages
          git config --global user.email "servbul@yandex.ru"
          git config --global user.name "GH Actions Bot"
          git add -A
          git commit --allow-empty -m "Deploy revision $GITHUB_SHA" && git push
